<?php

use Illuminate\Database\Seeder;
use Carbon\Carbon;

class BanksTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('banks')->insert([
            ['name_bank' => 'ธนาคารเพื่อการเกษตรและสหกรณ์การเกษตร',
            'short_bank' => 'baac',
			'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
			'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            ['name_bank' => 'ธนาคารกรุงศรีอยุธยา',
            'short_bank' => 'bay',
			'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
			'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            ['name_bank' => 'ธนาคารกรุงเทพ',
            'short_bank' => 'bbl',
			'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
			'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            ['name_bank' => 'ธนาคารบีเอ็นพี พารีบาส์',
            'short_bank' => 'bnp',
			'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
			'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            ['name_bank' => 'แบงค์ออฟอเมริกา',
            'short_bank' => 'boa',
			'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
			'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            ['name_bank' => 'ธนาคารเครดิต อากริโคล',
            'short_bank' => 'cacib',
			'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
			'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            ['name_bank' => 'ธนาคาร ซีไอเอ็มบี ไทย',
            'short_bank' => 'cimb',
			'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
			'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            ['name_bank' => 'ซิตี้แบงก์',
            'short_bank' => 'citi',
			'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
			'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            ['name_bank' => 'ธนาคารดอยซ์แบงก์',
            'short_bank' => 'db',
			'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
			'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            ['name_bank' => 'ธนาคารอาคารสงเคราะห์',
            'short_bank' => 'ghb',
			'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
			'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            ['name_bank' => 'ธนาคารออมสิน',
            'short_bank' => 'gsb',
			'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
			'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            ['name_bank' => 'ธนาคารเอชเอสบีซี ประเทศไทย',
            'short_bank' => 'hsbc',
			'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
			'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            ['name_bank' => 'ธนาคารอิสลามแห่งประเทศไทย',
            'short_bank' => 'ibank',
			'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
			'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            ['name_bank' => 'ธนาคารไอซีบีซี (ไทย)',
            'short_bank' => 'icbc',
			'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
			'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            ['name_bank' => 'เจพีมอร์แกนเชส',
            'short_bank' => 'jpm',
			'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
			'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            ['name_bank' => 'ธนาคารกสิกรไทย',
            'short_bank' => 'kbank',
			'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
			'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            ['name_bank' => 'ธนาคารเกียรตินาคิน',
            'short_bank' => 'kk',
			'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
			'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            ['name_bank' => 'ธนาคารกรุงไทย',
            'short_bank' => 'ktb',
			'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
			'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            ['name_bank' => 'ธนาคารแลนด์ แอนด์ เฮ้าส์',
            'short_bank' => 'lhb',
			'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
			'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            ['name_bank' => 'ธนาคารมิซูโฮ จํากัด',
            'short_bank' => 'mb',
			'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
			'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            ['name_bank' => 'ธนาคาร เมกะ สากลพาณิชย์ จํากัด',
            'short_bank' => 'mega',
			'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
			'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            ['name_bank' => 'ธนาคารโตเกียว-มิตซูบิชิ ยูเอฟเจ',
            'short_bank' => 'mufg',
			'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
			'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            ['name_bank' => 'รอยัล แบงก์ ออฟ สกอตแลนด์',
            'short_bank' => 'rbs',
			'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
			'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            ['name_bank' => 'ธนาคารสแตนดาร์ดชาร์เตอร์ด',
            'short_bank' => 'sc',
			'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
			'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            ['name_bank' => 'ธนาคารไทยพาณิชย์',
            'short_bank' => 'scb',
			'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
			'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            ['name_bank' => 'ซูมิโตโม มิตซุย แบงกิ้ง คอร์ปอเรชั่น',
            'short_bank' => 'smbc',
			'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
			'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            ['name_bank' => 'ธนาคารธนชาต',
            'short_bank' => 'tbank',
			'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
			'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            ['name_bank' => 'ธนาคารไทยเครดิต',
            'short_bank' => 'tcrb',
			'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
			'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            ['name_bank' => 'ธนาคารทิสโก้',
            'short_bank' => 'tisco',
			'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
			'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            ['name_bank' => 'ธนาคารทหารไทย',
            'short_bank' => 'tmb',
			'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
			'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            ['name_bank' => 'ธนาคาร ยูโอบี',
            'short_bank' => 'uob',
			'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
			'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
        ]);
	

	
	
	
	
	
	
	
	
	
	
	

    }
}
